-- [ ALTERNATIVE / MANUAL TEXTURES ] Spec alternatives, legacy skins, and CUSTOM entries.
-- Part of textureConfigFallback; load after RaceFaction; Extra atlas appends after this file.

EPF_CustomSkins_Definitions = EPF_CustomSkins_Definitions or {}
local D = EPF_CustomSkins_Definitions
D.textureConfigFallback = D.textureConfigFallback or {}

local entries = {
    { id = "dkbloodbbb", class = "DEATHKNIGHT", name = "dk_blood-by-benjiro_blue", ext = "png", displayName = "Blood by Benjiro Blue",
        layout = {
            layers = {
                {
                    width = 280,
                    height = 163,
                    leftTexCoord = 0/512,
                    rightTexCoord = 512/512,
                    topTexCoord = 216/512,
                    bottomTexCoord = 512/512,
                    pointOffset = { 190, -2 },
                },
            },
        },
    },
    { id = "dkfrostbbb", class = "DEATHKNIGHT", name = "dk_frost-by-benjiro_blue", ext = "png", displayName = "Frost by Benjiro Blue",
        layout = {
            layers = {
                {
                    width = 280,
                    height = 163,
                    leftTexCoord = 0/512,
                    rightTexCoord = 512/512,
                    topTexCoord = 216/512,
                    bottomTexCoord = 512/512,
                    pointOffset = { 190, -12 },
                },
            },
        },
    },
    { id = "dhdevdevou", class = "DEMONHUNTER", name = "dh_devourer", ext = "png", displayName = "Devourer Horns",
        layout = "top",
        pointOffset = { 170, 0 },
    },
    { id = "druidnight", class = "DRUID", name = "druid_balance", ext = "png", displayName = "Night Owl",
        layout = "top",
    },
    { id = "druidfangs", class = "DRUID", name = "druid_feral", ext = "png", displayName = "Fangs of Ashamane",
        layout = "bot",
    },
    { id = "druidsavag", class = "DRUID", name = "druid_feral_savage", ext = "png", displayName = "Savage Feral Beast",
        layout = "top",
    },
    { id = "druidincar", class = "DRUID", name = "druid_feral_savage", ext = "png", displayName = "Incarnation of Nightmare",
        layout = "bot",
    },
    { id = "druidstone", class = "DRUID", name = "druid_guardian", ext = "png", displayName = "Stonepaw",
        layout = "bot",
    },
    { id = "druidwarde", class = "DRUID", name = "druid_restoration", ext = "png", displayName = "Warden's Crown",
        layout = "top",
    },
    { id = "druidalpha", class = "DRUID", name = "druid_guardian&restoration", ext = "png", displayName = "Alpha Claws",
        layout = "top",
    },
    { id = "druidgnarl", class = "DRUID", name = "druid_guardian&restoration", ext = "png", displayName = "Gnarled Roots",
        layout = "bot",
    },
    { id = "druidold", class = "DRUID", name = "druid", ext = "png", displayName = "Druid old",
        layout = "bot",
    },
    { id = "hunteeagle", class = "HUNTER", name = "hunter_mm_eagle", ext = "png", displayName = "Eagle Hunter",
        layout = "top",
    },
    { id = "hunteazure", class = "HUNTER", name = "hunter_mm_white", ext = "png", displayName = "Azure Thas'dorah",
        layout = "top",
    },
    { id = "hunteazure1", class = "HUNTER", name = "hunter_mm_white", ext = "png", displayName = "Azure Eagle",
        layout = "bot",
    },
    { id = "huntenelft", class = "HUNTER", name = "hunter_mm_banshee", ext = "png", displayName = "Nelf Thas'dorah",
        layout = "top",
    },
    { id = "huntebansh", class = "HUNTER", name = "hunter_mm_banshee", ext = "png", displayName = "Banshee Redemption",
        layout = "bot",
    },
    { id = "huntetalon", class = "HUNTER", name = "hunter_survival", ext = "png", displayName = "Talonclawer",
        layout = "top",
        pointOffset = { 178, 0 },
    },
    { id = "monkzenle", class = "MONK", name = "monk", ext = "png", displayName="Zen Legacy",
        layout = "top",
        pointOffset = { 172, 10 },
    },
    { id = "monkniuza", class = "MONK", name = "monk", ext = "png", displayName="Niuzao Spirit",
        layout = "bot",
        pointOffset = { 160, 0 },
    },
    { id = "paladinbas", class = "PALADIN", name = "paladin_base&holy", ext = "png",
        layout = "top",
        pointOffset = { 170, 0 },
    },
    { id = "paladjudge", class = "PALADIN", name = "paladin_protection", ext = "png", displayName="Judgement Charger",
        layout = "top",
        pointOffset = { 192, -8 },
        restIconOffset = { 210, 0 },
    },
    { id = "paladashbr", class = "PALADIN", name = "paladin_retribution", ext = "png", displayName="Ashbringer Judgement",
        layout = "bot",
    },
    { id = "prieslegac", class = "PRIEST", name = "priest", ext = "png", displayName = "Legacy priest",
        layout = "bot",
    },
    { id = "priestomek", class = "PRIEST", name = "priest_extras", ext = "png", displayName = "Tomekeeper's Spire",
        layout = "top",
    },
    { id = "priessacre", class = "PRIEST", name = "priest_extras", ext = "png", displayName = "Sacred disciple",
        layout = "bot",
    },
    { id = "priesdarkd", class = "PRIEST", name = "priest_shadow", ext = "png", displayName = "Dark devotion",
        layout = "bot",
    },
    { id = "priesxalat", class = "PRIEST", name = "priest_black_empire", ext = "png", displayName = "Xal'atath Blade",
        layout = "top",
    },
    { id = "priesblack", class = "PRIEST", name = "priest_black_empire", ext = "png", displayName = "Black Empire",
        layout = "bot",
    },
    { id = "roguekings", class = "ROGUE", name = "rogue_assassination", ext = "png", displayName = "Kingslayer",
        layout = "bot",
    },
    { id = "roguedread", class = "ROGUE", name = "rogue_outlaw", ext = "png", displayName = "Dreadblades",
        layout = "bot",
    },
    { id = "warloredhe", class = "WARLOCK", name = "warlock_demonhead", ext = "png", displayName = "Warlock (Old Red)",
        layout = "top",
    },
    { id = "warlopurhe", class = "WARLOCK", name = "warlock_demonhead", ext = "png", displayName = "Warlock (Old Purple)",
        layout = "bot",
    },
    { id = "felcofelco", class = "WARLOCK", name = "fel_corruption", ext = "png", displayName = "Fel corruption",
        layout = "dual"
    },
    { id = "destrinfer", class = "WARLOCK", name = "warlock_inferno", ext = "png", displayName = "Inferno Succubus",
        layout = "bot",
        pointOffset = { 172, 6 },
    },
    { id = "destrintop", class = "WARLOCK", name = "warlock_inferno", ext = "png", displayName = "Infernal Ascendant",
        layout = "top",
        pointOffset = { 172, 6 },
    },
    { id = "corsapirat", class = "CUSTOM", name = "corsairs", ext = "png", displayName = "Pirate",
        layout = "top",
    },
    { id = "corsacorsa", class = "CUSTOM", name = "corsairs", ext = "png", displayName = "Corsair",
        layout = "bot",
    },
    { id = "voidshado", class = "CUSTOM", name = "void", ext = "png", displayName = "Void Shadow",
        layout = "bot",
        pointOffset = { 170, 0 },
    },
    { id = "voidmatte", class = "CUSTOM", name = "void", ext = "png", displayName = "Void Matter",
        layout = "top",
        pointOffset = { 170, 0 },
    },
    -- [ MANUAL-ONLY ] No class/race/spec; never auto-selected.
    { id = "blackblack", class = "CUSTOM", name = "blackdragon", ext = "png", displayName = "Black Dragon",
        layout = "dual",
    },
}

for _, entry in ipairs(entries) do
    D.textureConfigFallback[#D.textureConfigFallback + 1] = entry
end