-- [ ALTERNATIVE / MANUAL TEXTURES ] Spec alternatives, legacy skins, and CUSTOM entries.
-- Part of textureConfigFallback; load after RaceFaction; Extra atlas appends after this file.

EPF_CustomSkins_Definitions = EPF_CustomSkins_Definitions or {}
local D = EPF_CustomSkins_Definitions
D.textureConfigFallback = D.textureConfigFallback or {}

local entries = {
    { class = "DEATHKNIGHT", spec = 251, name = "dk_frost-by-benjiro_blue", ext = "png", displayName = "Frost by Benjiro Blue",
        layout = {
            layers = {
                {
                    width = 280,
                    height = 163,
                    leftTexCoord = 0/512,
                    rightTexCoord = 512/512,
                    topTexCoord = 216/512,
                    bottomTexCoord = 512/512,
                    pointOffset = { 190, -12 },
                },
            },
        },
    },
    { class = "DEMONHUNTER", spec = 1480, name = "dh_devourer", ext = "png", displayName = "Devourer Horns",
        layout = "top",
        pointOffset = { 170, 0 },
    },
    { class = "DRUID", name = "druid_balance", ext = "png", displayName = "Night Owl",
        layout = "top",
    },
    { class = "DRUID", name = "druid_feral", ext = "png", displayName = "Fangs of Ashamane",
        layout = "bot",
    },
    { class = "DRUID", name = "druid_feral_savage", ext = "png", displayName = "Savage Feral Beast",
        layout = "top",
    },
    { class = "DRUID", name = "druid_feral_savage", ext = "png", displayName = "Incarnation of Nightmare",
        layout = "bot",
    },
    { class = "DRUID", name = "druid_guardian", ext = "png", displayName = "Stonepaw",
        layout = "bot",
    },
    { class = "DRUID", name = "druid_restoration", ext = "png", displayName = "Warden's Crown",
        layout = "top",
    },
    { class = "DRUID", name = "druid_guardian&restoration", ext = "png", displayName = "Alpha Claws",
        layout = "top",
    },
    { class = "DRUID", name = "druid_guardian&restoration", ext = "png", displayName = "Gnarled Roots",
        layout = "bot",
    },
    { class = "DRUID", name = "druid", ext = "png", displayName = "Druid old",
        layout = "bot",
    },
    { class = "HUNTER", name = "hunter_mm_eagle", ext = "png", displayName = "Eagle Hunter",
        layout = "top",
    },
    { class = "HUNTER", name = "hunter_mm_white", ext = "png", displayName = "Azure Thas'dorah",
        layout = "top",
    },
    { class = "HUNTER", name = "hunter_mm_white", ext = "png", displayName = "Azure Eagle",
        layout = "bot",
    },
    { class = "HUNTER", name = "hunter_mm_banshee", ext = "png", displayName = "Nelf Thas'dorah",
        layout = "top",
    },
    { class = "HUNTER", name = "hunter_mm_banshee", ext = "png", displayName = "Banshee Redemption",
        layout = "bot",
    },
    { class = "HUNTER", name = "hunter_survival", ext = "png", displayName = "Talonclawer",
        layout = "top",
        pointOffset = { 178, 0 },
    },
    { class = "MONK", name = "monk", ext = "png", displayName="Zen Legacy",
        layout = "top",
        pointOffset = { 172, 10 },
    },
    { class = "MONK", name = "monk", ext = "png", displayName="Niuzao Spirit",
        layout = "bot",
        pointOffset = { 160, 0 },
    },
    { class = "PALADIN", name = "paladin_base&holy", ext = "png",
        layout = "top",
        pointOffset = { 170, 0 },
    },
    { class = "PALADIN", name = "paladin_protection", ext = "png", displayName="Judgement Charger",
        layout = "top",
        pointOffset = { 192, -8 },
        restIconOffset = { 210, 0 },
    },
    { class = "PALADIN", name = "paladin_retribution", ext = "png", displayName="Ashbringer Judgement",
        layout = "bot",
    },
    { class = "PRIEST", name = "priest", ext = "png", displayName = "Legacy priest",
        layout = "bot",
    },
    { class = "PRIEST", name = "priest_extras", ext = "png", displayName = "Tomekeeper's Spire",
        layout = "top",
    },
    { class = "PRIEST", name = "priest_extras", ext = "png", displayName = "Sacred disciple",
        layout = "bot",
    },
    { class = "PRIEST", name = "priest_shadow", ext = "png", displayName = "Dark devotion",
        layout = "bot",
    },
    { class = "PRIEST", name = "priest_black_empire", ext = "png", displayName = "Xal'atath Blade",
        layout = "top",
    },
    { class = "PRIEST", name = "priest_black_empire", ext = "png", displayName = "Black Empire",
        layout = "bot",
    },
    { class = "ROGUE", name = "rogue_assassination", ext = "png", displayName = "Kingslayer",
        layout = "bot",
    },
    { class = "ROGUE", name = "rogue_outlaw", ext = "png", displayName = "Dreadblades",
        layout = "bot",
    },
    { class = "WARLOCK", name = "warlock_red", ext = "png", displayName = "Warlock (Old Red)", layout = "dual" },
    { class = "WARLOCK", name = "fel_corruption", ext = "png", displayName = "Fel corruption", layout = "dual" },
    { class = "WARLOCK", name = "destro_succubus", ext = "png", displayName = "Inferno Succubus",
        layout = { preset = "dual", layers = { { pointOffset = { 42, 6 } }, { pointOffset = { 172, 6 } } } },
    },
    { class = "CUSTOM", name = "corsairs", ext = "png", displayName = "Pirate",
        layout = "top",
    },
    { class = "CUSTOM", name = "corsairs", ext = "png", displayName = "Corsair",
        layout = "bot",
    },
    { class = "CUSTOM", name = "void", ext = "png", displayName = "Void Shadow",
        layout = "bot",
        pointOffset = { 170, 0 },
    },
    { class = "CUSTOM", name = "void", ext = "png", displayName = "Void Matter",
        layout = "top",
        pointOffset = { 170, 0 },
    },
    -- [ MANUAL-ONLY ] No class/race/spec; never auto-selected.
    { class = "CUSTOM", name = "blackdragon", ext = "png", displayName = "Black Dragon", layout = "dual" },
}

for _, entry in ipairs(entries) do
    D.textureConfigFallback[#D.textureConfigFallback + 1] = entry
end
